### ISSUE TITLE
这个插件少一个时间区间大小控制的功能

### ISSUE THREAD

**Issue by xkrumeng** [ydwan/vue-calendar#1]
这个插件少一个时间区间大小控制的功能，比如我想控制选择的日期区间是在60天之内

**Comment by ydwan** [comment]
额，少年。目前这个插件有两种方式，实现你要的结果。
1、通过 begin 和 end 去限制 60 天。
2、通过 usableEnable 和 usableList ，限制能选择 60 天的具体元素。
以上都是props，并且需要自己去计算出理想的 60 天。
